### ISSUE TITLE
"to_url" method returns string with comma and apostrophe

### ISSUE THREAD

**Issue by sigerello** [rsl/stringex#9]
I have next Japanease and Russian strings:
    "AVアンプ、ホームシアターシステム、スピーカーシステム等".to_url
    "У лукоморья дуб зеленый".to_url
This returns:
    avanpu,-homusiatasisutemu,-supikasisutemudeng
    u-lukomor'ia-dub-zielienyi
I think it's no good to have commas or apostrophes in the url.
Maybe will be fine to add somethig like that to the end of "to_url" method:
    .gsub(/[^a-zA-Z0-9-]/, '')
or just add standard
    .parameterize
What do you think about that?

**Comment by schneikai** [comment]
Hey! Sorry if this isn't the right place but I have problems creating a valid slug from a string with a apostrophe.
This: ```URI::parse("http://www.foo.com/#{'oma is` kalt'.to_url}")```
gives me: ```URI::InvalidURIError: bad URI(is not URI?): http://www.foo.com/oma-is`-kalt```
I'm using Stringex 2.6.0 on Ruby 1.9.3. Stringex works greate otherwise and I would like to keep it. I'm just not sure what's the right way to fix this. Should I just gsub the apostrophe?
